### ISSUE TITLE
Rename to TCPTuner

### ISSUE THREAD

**Issue by lukehsiao** [Gasparila/TCPvil#10]
Some renaming is in order. We will want to update the name wherever we use it in:
- [x] the kernel module
- [x] the GUI
- [x] the README
- [x] The GitHub Repo itself (<-- this one is all you, Kevin)

**Comment by lukehsiao** [comment]
Goin to leave this open until the repo name changed, then you can close this. @Gasparila

**Comment by Gasparila** [comment]
Repo changed
