### ISSUE TITLE
Expose Parameters of ip-route

### ISSUE THREAD

**Issue by lukehsiao** [Gasparila/TCPvil#3]
I dropped by Keith's office hours, and we should try to expose as many of these:
![image](https://cloud.githubusercontent.com/assets/7573542/12965141/e5ec7ae8-d008-11e5-9ff9-8bb52db64c75.png)
that are relevant to congestion control.

**Comment by lukehsiao** [comment]
I'm a little confused about how to expose these. I do not see how these influence TCPvil, or if they do at all. 

The other complication is that I believe these modify parameters on a per-route basis, since it is modifying the routing table. [Example](http://unix.stackexchange.com/questions/210367/changing-the-tcp-rto-value-in-linux). So, really, it seems that our GUI will probably just be issuing various ip route commands. Should we just have every option modifying every entry in the routing table?

**Comment by Gasparila** [comment]
Yeah I don't see how they are useful. I mean... we could have buttons that just call iproute but I don't know why you would do that

**Comment by Gasparila** [comment]
All ip route params implemented though some cannot be used together
